MDBoxLayout:
    orientation: 'vertical'
    MDTopAppBar:
        title: "Oussama Sat Pro AI"
        elevation: 4
        left_action_items: [["satellite-variant", lambda x: None]]
    
    MDLabel:
        id: status_label
        text: "En attente de connexion USB..."
        halign: "center"
        theme_text_color: "Custom"
        text_color: 0, 1, 0, 1
        font_style: "H6"

    MDGridLayout:
        cols: 2
        padding: dp(20)
        spacing: dp(20)
        MDRaisedButton:
            text: "STARSAT"
            on_release: app.action_flash("Starsat")
        MDRaisedButton:
            text: "GEANT"
            on_release: app.action_flash("Geant")
