name: Final Build Fix
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install System Tools
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev           libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev           lib32z1 lib32ncurses6 lib32stdc++6 # مكتبات الـ 32 بت اللازمة لـ aidl
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          # تنظيف أي مخلفات قديمة وبناء نسخة Debug
          buildozer android clean
          yes | buildozer android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Oussama-Sat-App-v1
          path: bin/*.apk
